version: '3'

services:

  simulated-annealing:
    build: .
    tty: true
    stdin_open: true
    image: simulated-annealing
    container_name: simulated-annealing
    volumes:
      - ./simulated-annealing:/app
    command: >
      bash -c "cd /app &&
      ./waf configure --lp-lib=soplex --interval-lib=gaol --lp-lib=soplex &&
      ./waf install &&
      ./__build__/src/ibexopt benchs/optim/medium/ex14_2_7.bch --random-seed=1 >> commands.log &&
      tail -f /dev/null"

  hill-climbing:
    build: .
    tty: true
    stdin_open: true
    image: hill-climbing
    container_name: hill-climbing
    volumes:
      - ./hill-climbing:/app
    command: >
      bash -c "cd /app &&
      ./waf configure --lp-lib=soplex --interval-lib=gaol --lp-lib=soplex &&
      ./waf install &&
      ./__build__/src/ibexopt benchs/optim/medium/ex14_2_7.bch --random-seed=1 >> commands.log &&
      tail -f /dev/null"

  abstaylor:
    build: .
    tty: true
    stdin_open: true
    image: abstaylor
    container_name: abstaylor
    volumes:
      - ./abstaylor:/app
    command: >
      bash -c "cd /app &&
      ./waf configure --lp-lib=soplex --interval-lib=gaol --lp-lib=soplex &&
      ./waf install &&
      ./__build__/src/ibexopt benchs/optim/medium/ex14_2_7.bch --random-seed=1 >> commands.log &&
      tail -f /dev/null"