#------------- VERSION -------------#
version: '3'
services:
  simulated-annealing:
    build: .
    tty: true
    stdin_open: true
    image: simulated-annealing
    container_name: simulated-annealing
    volumes:
      - ./simulated-annealing:/app
  hill-climbing:
    build: .
    tty: true
    stdin_open: true
    image: hill-climbing
    container_name: hill-climbing
    volumes:
      - ./hill-climbing:/app
  abstaylor:
    build: .
    tty: true
    stdin_open: true
    image: abstaylor
    container_name: abstaylor
    volumes:
      - ./abstaylor:/app