version: "3"

services:
  simulated-annealing:
    build: .
    tty: true
    stdin_open: true
    image: simulated-annealing
    container_name: simulated-annealing
    volumes:
      - ./simulated-annealing:/app
    command: >
      bash -c "cd /app &&
      ./waf configure --lp-lib=soplex --interval-lib=gaol --lp-lib=soplex &&
      ./waf install &&
      ./__build__/src/ibexopt benchs/optim/medium/ex14_2_7.bch --random-seed=1 >> commands.log &&
      tail -f /dev/null"
    deploy:
      resources:
        limits:
          cpus: "1.0"

  simulated-annealing-joa:
    build: .
    tty: true
    stdin_open: true
    image: simulated-annealing-joa
    container_name: simulated-annealing-joa
    volumes:
      - ./simulated-annealing-joa:/app
    command: >
      bash -c "cd /app &&
      ./waf configure --lp-lib=soplex --interval-lib=gaol --lp-lib=soplex &&
      ./waf install &&
      ./__build__/src/ibexopt benchs/optim/medium/ex14_2_7.bch --random-seed=1 >> commands.log &&
      tail -f /dev/null"
    deploy:
      resources:
        limits:
          cpus: "1.0"

  hill-climbing:
    build: .
    tty: true
    stdin_open: true
    image: hill-climbing
    container_name: hill-climbing
    volumes:
      - ./hill-climbing:/app
    command: >
      bash -c "cd /app &&
      ./waf configure --lp-lib=soplex --interval-lib=gaol --lp-lib=soplex &&
      ./waf install &&
      ./__build__/src/ibexopt benchs/optim/medium/ex14_2_7.bch --random-seed=1 >> commands.log &&
      tail -f /dev/null"
    deploy:
      resources:
        limits:
          cpus: "1.0"

  abstaylor:
    build: .
    tty: true
    stdin_open: true
    image: abstaylor
    container_name: abstaylor
    volumes:
      - ./abstaylor:/app
    command: >
      bash -c "cd /app &&
      ./waf configure --lp-lib=soplex --interval-lib=gaol --lp-lib=soplex &&
      ./waf install &&
      ./__build__/src/ibexopt benchs/optim/medium/ex14_2_7.bch --random-seed=1 >> commands.log &&
      tail -f /dev/null"
    deploy:
      resources:
        limits:
          cpus: "1.0"

  simulated-annealing-parallel:
    build: .
    tty: true
    stdin_open: true
    image: simulated-annealing-parallel
    container_name: simulated-annealing-parallel
    volumes:
      - ./simulated-annealing-parallel:/app
    command: >
      bash -c "cd /app &&
      ./waf configure --lp-lib=soplex --interval-lib=gaol --lp-lib=soplex &&
      ./waf install &&
      ./__build__/src/ibexopt benchs/optim/medium/ex14_2_7.bch --random-seed=1 >> commands.log &&
      tail -f /dev/null"
    deploy:
      resources:
        limits:
          cpus: "5.0"

  pruebas:
    build: .
    tty: true
    stdin_open: true
    image: pruebas
    container_name: pruebas
    volumes:
      - ./pruebas:/app
    command: >
      bash -c "cd /app &&
      g++ --std=c++11 -pthread main.cpp -o main &&
      ./main &&
      tail -f /dev/null"
    deploy:
      resources:
        limits:
          cpus: "5.0"
